# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 692818fe546b56a9fab8709d713994091df828d8a24346bcb2a0fe046e35ddcf61f8069e88dac55e0645315a1af20204a8a93739e414ac560458748570a8dbc1

test:
  secret_key_base: 70ae3f91cbf439d9997d94c8efa3d335bad5deef6e5b2436a7e07fd8e94d4f7c6d2d77f08cd29ad388bd2c91e30a4f004b45e99f83024041abfd01e67ee0c07e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
